Fix/tao 9835/fix replace result namespace
oat-sa/extension-tao-outcomelti pull request #50
Opened 2020-09-02 13:42 UTC by siwane

In order to follow ltiv1p1 spec, replaceResult xml must be adapted to follow specifications.

LTI specificications: https://www.imsglobal.org/specs/ltiv1p1p1/implementation-guide#toc-26
Ticket: https://oat-sa.atlassian.net/browse/TAO-9835

2020-09-02 14:54 UTC, mike-ionut-mihai-sandu-tao commented on test/Unit/helpers/LtiBasicOutcomeTest.php
> +}
\n

2020-09-02 14:54 UTC, mike-ionut-mihai-sandu-tao commented on manifest.php
> +    'version' => '3.4.3',
why from '3.4.1', to '3.4.3', is '3.4.2', used?

2020-09-02 14:54 UTC, mike-ionut-mihai-sandu-tao commented on test/Unit/helpers/LtiBasicOutcomeTest.php
> +        $sourcedId = 'toto';
:)

2020-09-02 14:54 UTC, mike-ionut-mihai-sandu-tao commented on test/Unit/helpers/LtiBasicOutcomeTest.php
> +class LtiBasicOutcomeTest extends TestCase
please run phpcs on this

2020-09-02 16:31 UTC, siwane commented on test/Unit/helpers/LtiBasicOutcomeTest.php
> +class LtiBasicOutcomeTest extends TestCase
done

2020-09-02 16:32 UTC, siwane commented on manifest.php
> +    'version' => '3.4.3',
good catch

2020-09-02 16:32 UTC, siwane commented on test/Unit/helpers/LtiBasicOutcomeTest.php
> +}
done

2020-09-03 14:03 UTC, gabrielfs7 reviewed
Just a suggestion to build this XML body in a central place, cause now we have to fix 3 places.

- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-09-04 14:08 UTC, gabrielfs7 commented on manifest.php
> +    'version' => '3.4.2',
Isn it a breaking change now that File was removed? One way it to keep the file and do a delegate for the new factory inside. Wdyt?

2020-09-04 14:09 UTC, gabrielfs7 commented on models/classes/class.LtiBasicOutcome.php
>                  //common_Logger::i("Preparing POX message for the outcome service :".$message."\n");
Not related to your PR, but I think we can remove this comment.

2020-09-04 14:09 UTC, gabrielfs7 commented on models/classes/class.LtiBasicOutcome.php
> +                $ltiOutcomeXmlFactory = $this->getLtiOutcomeXmlFactory();
Thanks 🙇

2020-09-07 09:24 UTC, gabrielfs7 commented on models/classes/class.LtiBasicOutcome.php
> +                    'replaceResultRequest'
This should be language parameter or omitted, no?

2020-09-07 09:26 UTC, gabrielfs7 approved these changes
LGTM, just one parameter order it wrong as I mentioned in the comment.

2020-09-07 09:26 UTC, mike-ionut-mihai-sandu-tao commented on models/classes/class.LtiBasicOutcome.php
> +                    'replaceResultRequest'
fixed

2020-09-08 08:02 UTC, boajer requested changes
A minor change required

2020-09-08 08:02 UTC, boajer commented on models/classes/class.LtiBasicOutcome.php
> +        $this->getServiceLocator()->get(LtiOutcomeXmlFactory::class);
I think that is the must here
```suggestion
       return $this->getServiceLocator()->get(LtiOutcomeXmlFactory::class);
```

2020-09-09 13:49 UTC, boajer commented on manifest.php
> +        'taoLti' => '>=5.0.0',
```suggestion
        'taoLti' => '>=11.12.0',
```
due to introduction of `LtiOutcomeXmlFactory`

2020-09-09 13:54 UTC, boajer commented on models/classes/class.LtiBasicOutcome.php
> +                    uniqid('', true)
If we are going towards random, I would prefer `Uuid::uuid4()`

2020-09-09 13:54 UTC, boajer requested changes
1 minor change needed + 1 recommendation for discussion :)

2020-09-10 07:27 UTC, mike-ionut-mihai-sandu-tao commented on models/classes/class.LtiBasicOutcome.php
> +                    uniqid('', true)
it was the previous way of computing the id , but let me check if i can implement effortless Uuid::uuid4()

2020-09-10 07:38 UTC, boajer approved these changes
LGFM

2020-09-10 07:56 UTC, merged