fix: remove unsupported split function
oat-sa/extension-tao-outcomelti pull request #58
Opened 2022-07-08 06:41 UTC by gabrielfs7

https://oat-sa.atlassian.net/browse/ADF-1097
https://oat-sa.atlassian.net/browse/ADF-1087
https://oat-sa.atlassian.net/browse/ADF-1105

## Goal 

Make the extension not dictating PHP version to easier our PHP maintenance, since the extension does not work in isolation and PHP version should be equally respected to all TAO extensions.

2022-07-25 11:40 UTC, wazelin requested changes

2022-07-25 11:40 UTC, wazelin commented on includes/ims-blti/OAuth.php
> +        $pairs = preg_split('/&/', $input);
```suggestion
        $pairs = explode('&', $input);
```

2022-07-25 11:40 UTC, wazelin commented on includes/ims-blti/OAuth.php
> +            $split = preg_split('/=/', $pair, 2);
```suggestion
            $split = explode('=', $pair, 2);
```

2022-09-27 15:55 UTC, hectoras approved these changes

2022-09-29 06:07 UTC, merged